/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static DADES.GestioLog.EscriureLog;
import DADES.gestioSQL;
import static DADES.gestioSQL.carregarUsuari;
import static DADES.gestioSQL.carregarUsuariPerNom;
import static DADES.gestioSQL.insertUsuari;
import static DADES.gestioSQL.modificarUsuari;
import MODEL.Usuari;
import MODEL.Usuari.TipusBan;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joaquin
 */
public class frmControlUsuaris extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmControlUsuaris.class.getName());
    private static ButtonGroup opcio = new ButtonGroup();
    DefaultTableModel mModelTaula = new DefaultTableModel();

    /**
     * Creates new form frmControlUsuaris
     */
    public frmControlUsuaris() {
        initComponents();
        opcio.add(btnCrea);
        opcio.add(btnModifica);
        btnCrea.setActionCommand("crear");
        btnModifica.setActionCommand("modificar");
        mModelTaula.addColumn("Usuari");
        mModelTaula.addColumn("Nom");
        mModelTaula.addColumn("Admin");
        mModelTaula.addColumn("Estat de ban");
        tblUsuaris.setModel(mModelTaula);
        ompleTaula();
    }

    private void ompleTaula() {
        mModelTaula.setRowCount(0);

        ArrayList<Usuari> usuaris = gestioSQL.carregarUsuari();
        String filtre = txtUsername.getText().trim();

        for (Usuari u : usuaris) {

            if (filtre.isEmpty() || u.getNom_usuari().contains(filtre)) {

                Object[] fila = new Object[4];
                fila[0] = u.getNom_usuari();
                fila[1] = u.getNom();
                fila[2] = u.isAdmin();
                fila[3] = u.getEstat();
                mModelTaula.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuaris = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContrasenya = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataNaixament = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numPunts = new javax.swing.JSpinner();
        cmbEstat = new javax.swing.JComboBox<>();
        txtDataBan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbAdmin = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtAccioActual = new javax.swing.JLabel();
        btnModifica = new javax.swing.JRadioButton();
        btnCrea = new javax.swing.JRadioButton();
        imgLogo = new javax.swing.JLabel();
        btnDataActual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        tblUsuaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuaris);

        jLabel1.setText("Usuari");

        jLabel2.setText("Nom");

        jLabel3.setText("Contrasenya");

        jLabel4.setText("Data naixament (dd/mm/aaaa)");

        jLabel5.setText("Punts");

        jLabel6.setText("Estat");

        jLabel7.setText("Data ban (dd/mm/aaaa hh:mm)");

        cmbEstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "active", "warned", "soft_ban", "hard_ban" }));
        cmbEstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstatActionPerformed(evt);
            }
        });

        jLabel8.setText("Admin");

        cmbAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        btnBuscar.setText("🔎");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtAccioActual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtAccioActual.setText("CREAR");

        btnModifica.setText("Modificar");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        btnCrea.setSelected(true);
        btnCrea.setText("Crear");
        btnCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaActionPerformed(evt);
            }
        });

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/logoCriticFy128p.png"))); // NOI18N
        imgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnDataActual.setText("📅");
        btnDataActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccioActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCrea, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(143, 143, 143)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscar))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnDataActual)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cmbEstat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(numPunts)
                                                    .addComponent(txtContrasenya)
                                                    .addComponent(txtDataNaixament, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDataBan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)))))
                        .addGap(81, 81, 81)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgLogo))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAccioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDataNaixament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(numPunts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbEstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDataBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDataActual))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrea)
                            .addComponent(btnAplicar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifica)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {
            Usuari u = carregarUsuariPerNom(txtUsername.getText());
            System.out.println(u.toString());
            txtName.setText(u.getNom());
            txtContrasenya.setText(u.getContrasenya());
            txtDataNaixament.setText(u.getData_naixament().format(format));
            numPunts.setValue(u.getPunts());
            cmbEstat.setSelectedItem(u.getEstat().toString());
            if (u.getEstat() != TipusBan.active) {
                txtDataBan.setText(u.getData_ban().toString());
                txtDataBan.setEnabled(true);
                btnDataActual.setEnabled(true);
            } else {
                txtDataBan.setEnabled(false);
                btnDataActual.setEnabled(false);
            }

            cmbAdmin.setSelectedItem(String.valueOf(u.isAdmin()));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Usuari inexistent, prova a crearel primer");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaActionPerformed
        String opcioSeleccionada = evt.getActionCommand();
        switch (opcioSeleccionada) {
            case "crear":
                txtAccioActual.setText("CREAR");
                break;
            case "modificar":
                txtAccioActual.setText("MODIFICAR");
                break;
        }
    }//GEN-LAST:event_btnCreaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        String opcioSeleccionada = evt.getActionCommand();
        switch (opcioSeleccionada) {
            case "crear":
                txtAccioActual.setText("CREAR");
                break;
            case "modificar":
                txtAccioActual.setText("MODIFICAR");
                break;
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        String opcioSeleccionada = opcio.getSelection().getActionCommand();
        DateTimeFormatter formatData = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        DateTimeFormatter formatDateTime = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        String username = txtUsername.getText();
        String name = txtName.getText();
        String contrasenya = txtContrasenya.getText();
        LocalDate dataNaixement = LocalDate.parse(txtDataNaixament.getText(), formatData);

        int punts = (int) numPunts.getValue();
        Usuari.TipusBan estat = Usuari.TipusBan.valueOf(cmbEstat.getSelectedItem().toString());
        
        LocalDateTime dataBan = LocalDateTime.parse(txtDataBan.getText(), formatDateTime);

        boolean admin = Boolean.parseBoolean(cmbAdmin.getSelectedItem().toString());

        Usuari u = new Usuari(username, name, contrasenya, dataNaixement, punts, estat, dataBan, admin);

        switch (opcioSeleccionada) {
            case "crear":
                try {
                    insertUsuari(u);
                    JOptionPane.showMessageDialog(this, "Creat l'usuari " + u.getNom_usuari());
                    EscriureLog("S'ha Creat l'usuari: " + u.getNom_usuari());
                    ompleTaula();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Parametres incorrectes o usuari ja existent");
                    ex.printStackTrace();

                }
                break;
            case "modificar":
                try {
                    if (u.getEstat() != Usuari.TipusBan.active) {

                    }
                    modificarUsuari(u);

                    JOptionPane.showMessageDialog(this, "Modificat l'usuari " + u.getNom_usuari());
                    EscriureLog("S'ha modificat l'usuari: " + u.getNom_usuari());
                    ompleTaula();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Parametres incorrectes");
                    ex.printStackTrace();

                }
                break;
        }

    }//GEN-LAST:event_btnAplicarActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        ompleTaula();
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void btnDataActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActualActionPerformed
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDateTime ara = LocalDateTime.now();
        txtDataBan.setText(ara.format(format));
    }//GEN-LAST:event_btnDataActualActionPerformed

    private void cmbEstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstatActionPerformed
        if(cmbEstat.getSelectedItem() != "active"){
            txtDataBan.setEnabled(true);
            btnDataActual.setEnabled(true);
        }
        else{
            txtDataBan.setEnabled(false);
            btnDataActual.setEnabled(false);
            txtDataBan.setText("");
        }
        
    }//GEN-LAST:event_cmbEstatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmControlUsuaris().setVisible(true));
    }

    public static void omplirTaula() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JRadioButton btnCrea;
    private javax.swing.JButton btnDataActual;
    private javax.swing.JRadioButton btnModifica;
    private javax.swing.JComboBox<String> cmbAdmin;
    private javax.swing.JComboBox<String> cmbEstat;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner numPunts;
    private javax.swing.JTable tblUsuaris;
    private javax.swing.JLabel txtAccioActual;
    private javax.swing.JTextField txtContrasenya;
    private javax.swing.JTextField txtDataBan;
    private javax.swing.JTextField txtDataNaixament;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
