/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rger Trulls
 */
public class frmDiccionari extends javax.swing.JFrame {

    private DefaultListModel<String> modelDiccionari = new DefaultListModel<>();
    private final String RUTA_DICCIONARI = "src/DADES/diccionari.txt"; // Ajusta la ruta segons la teva estructura
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmDiccionari.class.getName());

    /**
     * Creates new form frmDiccionari
     */
    public frmDiccionari() {
        initComponents();
        lstDiccionari.setModel(modelDiccionari);
        carregarDiccionari();
    }

    private void carregarDiccionari() {
        modelDiccionari.clear();
        File fitxer = new File(RUTA_DICCIONARI);

        if (!fitxer.exists()) {
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(fitxer))) {
            String paraula;
            while ((paraula = br.readLine()) != null) {
                if (!paraula.trim().isEmpty()) {
                    modelDiccionari.addElement(paraula);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error carregant diccionari: " + e.getMessage());
        }
    }

    private void afegirParaulaAlFitxer(String paraula) {
        try (PrintWriter pw = new PrintWriter(new FileWriter(RUTA_DICCIONARI, true))) {
            pw.println(paraula);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }

    private void accioAfegir() {
        String nova = JOptionPane.showInputDialog(this, "Introdueix la nova paraula:");
        if (nova != null && !nova.trim().isEmpty()) {
            String paraula = nova.trim();
            if (modelDiccionari.contains(paraula)) {
                JOptionPane.showMessageDialog(this, "Aquesta paraula ja existeix.");
                return;
            }
            modelDiccionari.addElement(paraula);
            reescriureFitxerComplet();
        }
    }

    private void accioModificar() {
        int index = lstDiccionari.getSelectedIndex();
        if (index != -1) {
            String antiga = modelDiccionari.getElementAt(index);
            String nova = JOptionPane.showInputDialog(this, "Modifica la paraula:", antiga);

            if (nova != null && !nova.trim().isEmpty()) {
                modelDiccionari.set(index, nova.trim());
                reescriureFitxerComplet();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una paraula de la llista per modificar.");
        }
    }

    private void accioEliminar() {
        int index = lstDiccionari.getSelectedIndex();
        if (index != -1) {
            int confirmacio = JOptionPane.showConfirmDialog(this, "Segur que vols eliminar la paraula?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirmacio == JOptionPane.YES_OPTION) {
                modelDiccionari.remove(index);
                reescriureFitxerComplet();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una paraula per eliminar.");
        }
    }

    private void reescriureFitxerComplet() {
        try (PrintWriter pw = new PrintWriter(new FileWriter("src/DADES/diccionari.txt", false))) { // false per sobreescriure
            for (int i = 0; i < modelDiccionari.size(); i++) {
                pw.println(modelDiccionari.getElementAt(i));
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el diccionari: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitol = new javax.swing.JLabel();
        btnAfegit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDiccionari = new javax.swing.JList<>();
        imgLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitol.setFont(new java.awt.Font("Liberation Serif", 1, 48)); // NOI18N
        lblTitol.setForeground(new java.awt.Color(102, 102, 255));
        lblTitol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitol.setText("DICCIONARI");
        lblTitol.setMaximumSize(new java.awt.Dimension(2000, 999));
        lblTitol.setMinimumSize(new java.awt.Dimension(0, 0));

        btnAfegit.setText("AFEGIR");
        btnAfegit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegitActionPerformed(evt);
            }
        });

        lstDiccionari.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        jScrollPane1.setViewportView(lstDiccionari);

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/logoCriticFy128p.png"))); // NOI18N
        imgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgLogo.setMaximumSize(new java.awt.Dimension(50, 50));
        imgLogo.setMinimumSize(new java.awt.Dimension(50, 50));
        imgLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgLogoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnAfegit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnAfegit)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgLogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMousePressed
        // TODO add your handling code here:
        frmPanelControl panel = new frmPanelControl();
        panel.setVisible(true);
        panel.setLocationRelativeTo(this);
        panel.toFront();
        this.dispose();
        frmDiccionari diccionari = new frmDiccionari();
        diccionari.setLocationRelativeTo(this);
        diccionari.setFocusable(false);
    }//GEN-LAST:event_imgLogoMousePressed

    private void btnAfegitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegitActionPerformed
        String[] opcions = {"Afegir", "Modificar", "Eliminar", "Cancel·lar"};
        int seleccio = JOptionPane.showOptionDialog(
                this,
                "Quina acció vols realitzar al diccionari?",
                "Gestió del Diccionari",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcions,
                opcions[0]);

        switch (seleccio) {
            case 0 ->
                accioAfegir();
            case 1 ->
                accioModificar();
            case 2 ->
                accioEliminar();
            default -> {
                /* No fer res si cancel·la */ }

        }
    }//GEN-LAST:event_btnAfegitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmDiccionari().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegit;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitol;
    private javax.swing.JList<String> lstDiccionari;
    // End of variables declaration//GEN-END:variables
}
