/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static CONTROLLER.Main.pelicules;
import static CONTROLLER.Main.series;
import static CONTROLLER.Main.videojocs;
import DADES.gestioSQL;
import MODEL.Contingut;
import MODEL.Pelicula;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquin
 */
public class frmHigherLower extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHigherLower.class.getName());
    private static gestioSQL gestioSql = new gestioSQL();

    /**
     * Creates new form frmHigherLower
     */
    private static Contingut c1;
    private static Contingut c2;
    private static int score = 0;

    public frmHigherLower() {
        initComponents();

        score = 0;
        updateScore();
        novaRonda();
        txtNota2.setVisible(false);

    }

    private void novaRonda() {
        c1 = gestioSql.carregarPeliculaAleatoria();
        c2 = gestioSql.carregarPeliculaAleatoria();

        carregarPeliculaEnImg(c1, img1, txtImage, txtNota);
        carregarPeliculaEnImg(c2, img2, txtImage2, txtNota2);
    }

    public void carregarPeliculaEnImg(
            Contingut c, javax.swing.JLabel labelImg, javax.swing.JLabel labelTitol, javax.swing.JLabel labelNota) {
        if (c == null) {
            labelTitol.setText("No disponible");
            labelNota.setText("0.00");
            labelImg.setIcon(new ImageIcon(getClass().getResource("/VIEW/placeHolderImg.png")));
            return;
        }

        labelTitol.setText(c.getTitol());
        labelNota.setText("Nota: " + String.format("%.2f", gestioSql.obtenirNotaContingut(c)));

        try {
            byte[] imgBytes = c.getImatge();

            if (imgBytes == null || imgBytes.length == 0) {
                labelImg.setIcon(new ImageIcon(getClass().getResource("/VIEW/placeHolderImg.png")));
                return;
            }

            ByteArrayInputStream bis = new ByteArrayInputStream(imgBytes);
            BufferedImage bImage = ImageIO.read(bis);

            if (bImage == null) {
                labelImg.setIcon(new ImageIcon(getClass().getResource("/VIEW/placeHolderImg.png")));
                return;
            }

            Image scaledImage = bImage.getScaledInstance(
                    labelImg.getWidth() > 0 ? labelImg.getWidth() : 245,
                    labelImg.getHeight() > 0 ? labelImg.getHeight() : 239,
                    Image.SCALE_SMOOTH
            );

            labelImg.setIcon(new ImageIcon(scaledImage));

        } catch (Exception e) {
            System.out.println("Error carregant imatge: " + e.getMessage());

            labelImg.setIcon(new ImageIcon(
                    getClass().getResource("/VIEW/logoCriticFy128p.png")
            ));
        }

    }

    private void updateScore() {
        txtPoints.setText("Score: " + score);
    }

    private void restartGame() {
        score = 0;
        updateScore();
        novaRonda();
        txtNota2.setVisible(false);
    }

    private void gameOver() {
        txtNota2.setVisible(true);
        int option = JOptionPane.showConfirmDialog(
                this,
                "Has perdut 😢\nScore final: " + score + "\nVols tornar a jugar?",
                "Game Over",
                JOptionPane.YES_NO_OPTION
        );

        if (option == JOptionPane.YES_OPTION) {
            restartGame();
        } else {
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        txtNom1 = new javax.swing.JLabel();
        txtNota = new javax.swing.JLabel();
        txtImage = new javax.swing.JLabel();
        txtImage2 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JLabel();
        btnHigher = new javax.swing.JButton();
        btnLower = new javax.swing.JButton();
        txtPoints = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/logoCriticFy128p.png"))); // NOI18N

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/logoCriticFy128p.png"))); // NOI18N
        img1.setAlignmentY(0.0F);
        img1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtNota.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNota.setText("0.00");
        txtNota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtImage.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        txtImage.setText("No ha carregat");

        txtImage2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        txtImage2.setText("No ha carregat");

        txtNota2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNota2.setText("0.00");
        txtNota2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHigher.setBackground(new java.awt.Color(160, 63, 65));
        btnHigher.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnHigher.setText("⬆️");
        btnHigher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHigherActionPerformed(evt);
            }
        });

        btnLower.setBackground(new java.awt.Color(60, 163, 165));
        btnLower.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLower.setText("⬇️");
        btnLower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLowerActionPerformed(evt);
            }
        });

        txtPoints.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPoints.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(img1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(txtImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHigher, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLower, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(txtNota2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHigher, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLower, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(txtPoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNom1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHigherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHigherActionPerformed
        if (c1 == null || c2 == null) {
            return;
        }

        double nota1 = gestioSql.obtenirNotaContingut(c1);
        double nota2 = gestioSql.obtenirNotaContingut(c2);

        if (nota1 <= nota2) {
            score++;
            updateScore();
            novaRonda();
        } else {
            gameOver();
        }

    }//GEN-LAST:event_btnHigherActionPerformed

    private void btnLowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLowerActionPerformed

        if (c1 == null || c2 == null) {
            return;
        }

        double nota1 = gestioSql.obtenirNotaContingut(c1);
        double nota2 = gestioSql.obtenirNotaContingut(c2);

        if (nota1 >= nota2) {
            score++;
            updateScore();
            novaRonda();
        } else {
            gameOver();
        }

    }//GEN-LAST:event_btnLowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHigherLower().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHigher;
    private javax.swing.JButton btnLower;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel txtImage;
    private javax.swing.JLabel txtImage2;
    private javax.swing.JLabel txtNom1;
    private javax.swing.JLabel txtNota;
    private javax.swing.JLabel txtNota2;
    private javax.swing.JLabel txtPoints;
    // End of variables declaration//GEN-END:variables
}
