/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLLER.Main;
import static CONTROLLER.Main.mod;
import static CONTROLLER.Main.usuariActual;
import DADES.GestioLog;
import DADES.gestioSQL;
import static DADES.gestioSQL.modificarUsuari;
import static MODEL.Style.temaClar;
import static MODEL.Style.temaFosc;
import MODEL.Usuari;
import MODEL.Usuari.TipusBan;
import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Joaquin
 */
public class frmLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmLogin.class.getName());

    /**
     * Creates new form frmLogin
     */
    private ButtonGroup btnEstil = new ButtonGroup();

    public frmLogin() {
        initComponents();
        btnEstil.add(btnClar);
        btnEstil.add(btnFosc);

        /*cambiaImatge();*/
    }

    /*private void cambiaImatge() {
        imgLogo.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("logoCriticFy128p_alternative.png")));
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        txtUsuari = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtContrassenya = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnClar = new javax.swing.JRadioButton();
        btnFosc = new javax.swing.JRadioButton();
        btnMostra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/logoCriticFy128p.png"))); // NOI18N
        imgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuariActionPerformed(evt);
            }
        });

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtContrassenya.setToolTipText("password");

        jLabel2.setText("Usuari");

        jLabel3.setText("Contrasenya");

        btnClar.setText("Tema Clar");
        btnClar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClarActionPerformed(evt);
            }
        });

        btnFosc.setSelected(true);
        btnFosc.setText("Tema Fosc");
        btnFosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoscActionPerformed(evt);
            }
        });

        btnMostra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMostra.setText("👁️");
        btnMostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuari, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtContrassenya, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostra)
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLogo)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrassenya, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostra))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegister)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFosc)))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        frmRegister register = new frmRegister();
        register.setVisible(true);
        register.setLocationRelativeTo(this);
        register.toFront();
        this.dispose();
        frmLogin login = new frmLogin();
        login.setLocationRelativeTo(this);
        login.setFocusable(false);

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String passText = new String(txtContrassenya.getPassword());
        String userText = txtUsuari.getText();

        Usuari u = gestioSQL.login(userText, passText);

        if (u != null) {
            usuariActual = u;

            // Verificació d'expiració de ban: Si la data ja ha passat, el tornem a fer "active"
            if (u.getEstat() != TipusBan.active && u.getData_ban() != null) {
                if (u.getData_ban().isBefore(LocalDateTime.now())) {
                    u.setEstat(TipusBan.active);
                    u.setData_ban(null);
                    try {
                        gestioSQL.modificarUsuari(u);
                    } catch (SQLException ex) {
                        logger.log(java.util.logging.Level.SEVERE, "Error actualitzant estat post-ban", ex);
                    }
                }
            }

            // Control de HARD BAN: Bloqueja l'entrada totalment
            if (u.getEstat() == TipusBan.hard_ban) {
                JOptionPane.showMessageDialog(this, "ACCÉS DENEGAT.\nEstàs sota un HARD BAN fins al: "
                        + u.getData_ban().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
                return;
            }

            // Redirecció segons el rol (Admin o Client)
            if (u.isAdmin()) {
                frmPanelControl fAdmin = new frmPanelControl();
                fAdmin.setVisible(true);
                GestioLog.EscriureLog(mod + ":\t" + " Usuari " + u.getNom_usuari() + "\t\tInicia sessio admin");
            } else {
                 frmPanelControl fAdmin = new frmPanelControl();
                fAdmin.setVisible(true);

                // Avis per WARNED: Només un avís informatiu
                if (u.getEstat() == TipusBan.warned) {
                    JOptionPane.showMessageDialog(fAdmin, "AVÍS DE COMPORTAMENT: " + u.getNom_usuari()
                            + "\nHas rebut una advertència per contingut inapropiat. \nSi continues així, el teu compte podria ser bloquejat temporalment.",
                            "Advertència del Sistema", JOptionPane.WARNING_MESSAGE);
                }

                // Avis per SOFT BAN: Restricció de funcionalitat
                if (u.getEstat() == TipusBan.soft_ban) {
                    JOptionPane.showMessageDialog(fAdmin, "Tens un SOFT BAN actiu. Podràs navegar però no podràs publicar ressenyes fins al: "
                            + u.getData_ban().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
                }

                GestioLog.EscriureLog(mod + ":\t" + " Usuari " + u.getNom_usuari() + "\t\tInicia sessio client");
            }

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Usuari o contrasenya incorrectes");
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    private void txtUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuariActionPerformed

    private void btnClarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClarActionPerformed
        temaClar(this);
    }//GEN-LAST:event_btnClarActionPerformed

    private void btnFoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoscActionPerformed
        temaFosc(this);
    }//GEN-LAST:event_btnFoscActionPerformed

    private void btnMostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraActionPerformed
        if (txtContrassenya.getEchoChar() == 0) {
            txtContrassenya.setEchoChar('•');
        } else {
            txtContrassenya.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_btnMostraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnClar;
    private javax.swing.JRadioButton btnFosc;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMostra;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtContrassenya;
    private javax.swing.JTextField txtUsuari;
    // End of variables declaration//GEN-END:variables
}
