/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static CONTROLLER.Main.usuariActual;
import DADES.gestioSQL;
import MODEL.Contingut;
import java.awt.Image;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Joaquin
 */
public class frmPanelControl extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPanelControl.class.getName());
    private static gestioSQL gestioSql = new gestioSQL();
    private static Contingut c;

    /**
     * Creates new form frmPanelControl
     */
    public frmPanelControl() {
        initComponents();
        txtNom.setText("Benvolgut  " + usuariActual.getNom_usuari() + "!");
        if (!usuariActual.isAdmin()) {
            panAdmin.show(false);
            panAdmin.disable();
            revalidate();
            repaint();
        }
        c = gestioSql.obtenirContingutAleatori();
        carregarContingutEnImg(c, img1, txtImage, txtNota);
    }

    public void carregarContingutEnImg(
            Contingut c,
            javax.swing.JLabel labelImg,
            javax.swing.JLabel labelTitol,
            javax.swing.JLabel labelNota) {

        if (c == null) {
            labelTitol.setText("No disponible");
            labelNota.setText("0.00");
            labelImg.setIcon(null);
            return;
        }

        labelTitol.setText(c.getTitol());
        labelNota.setText("Nota: " + String.format("%.2f", gestioSql.obtenirNotaContingut(c)));

        try {

            byte[] imgBytes = c.getImatge();

            if (imgBytes == null || imgBytes.length == 0) {
                labelImg.setIcon(null);
                return;
            }

            ByteArrayInputStream bis = new ByteArrayInputStream(imgBytes);
            BufferedImage bImage = ImageIO.read(bis);

            if (bImage == null) {
                labelImg.setIcon(null);
                return;
            }

            Image scaledImage = bImage.getScaledInstance(
                    labelImg.getWidth() > 0 ? labelImg.getWidth() : 245,
                    labelImg.getHeight() > 0 ? labelImg.getHeight() : 239,
                    Image.SCALE_SMOOTH
            );

            labelImg.setIcon(new ImageIcon(scaledImage));

        } catch (Exception e) {

            System.out.println("Error carregant imatge: " + e.getMessage());
            labelImg.setIcon(new ImageIcon(getClass().getResource("/VIEW/placeHolderImg.jpg")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAdmin = new javax.swing.JPanel();
        btnControlResenyes = new javax.swing.JButton();
        btnControlContingut = new javax.swing.JButton();
        btnControlUsuari = new javax.swing.JButton();
        btnDiccionari = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnModificarUsuari = new javax.swing.JButton();
        btnModificarUsuari1 = new javax.swing.JButton();
        btnAfegirResenya = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        img1 = new javax.swing.JLabel();
        txtImage = new javax.swing.JLabel();
        txtNota = new javax.swing.JLabel();
        txtNom = new javax.swing.JLabel();
        lblRating1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnControlResenyes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnControlResenyes.setText("Control resenyes");
        btnControlResenyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlResenyesActionPerformed(evt);
            }
        });

        btnControlContingut.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnControlContingut.setText("Control contingut");
        btnControlContingut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlContingutActionPerformed(evt);
            }
        });

        btnControlUsuari.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnControlUsuari.setText("Control usuaris");
        btnControlUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlUsuariActionPerformed(evt);
            }
        });

        btnDiccionari.setText("Diccionari 📚");
        btnDiccionari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiccionariActionPerformed(evt);
            }
        });

        btnLog.setText("Veure log 📘");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAdminLayout = new javax.swing.GroupLayout(panAdmin);
        panAdmin.setLayout(panAdminLayout);
        panAdminLayout.setHorizontalGroup(
            panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnControlUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panAdminLayout.createSequentialGroup()
                            .addComponent(btnControlContingut, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnControlResenyes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panAdminLayout.createSequentialGroup()
                        .addComponent(btnDiccionari, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAdminLayout.setVerticalGroup(
            panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnControlUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnControlContingut, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnControlResenyes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiccionari, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        btnLogOut.setText("Tanca Sessió");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnModificarUsuari.setBackground(new java.awt.Color(60, 63, 165));
        btnModificarUsuari.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModificarUsuari.setText("Higher or Lower ⬆️⬇️");
        btnModificarUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuariActionPerformed(evt);
            }
        });

        btnModificarUsuari1.setBackground(new java.awt.Color(160, 63, 65));
        btnModificarUsuari1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModificarUsuari1.setText("Editar Usuari ⚙️");
        btnModificarUsuari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuari1ActionPerformed(evt);
            }
        });

        btnAfegirResenya.setBackground(new java.awt.Color(235, 189, 52));
        btnAfegirResenya.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAfegirResenya.setText("Resenyes 🌟");
        btnAfegirResenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirResenyaActionPerformed(evt);
            }
        });

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/logoCriticFy128p.png"))); // NOI18N
        imgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/logoCriticFy128p.png"))); // NOI18N
        img1.setAlignmentY(0.0F);
        img1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtImage.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        txtImage.setText("No ha carregat");

        txtNota.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNota.setText("0.00");
        txtNota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtNom.setFont(new java.awt.Font("Liberation Serif", 1, 48)); // NOI18N
        txtNom.setForeground(new java.awt.Color(102, 102, 255));
        txtNom.setText("BENVOLGUT NOM!");
        txtNom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblRating1.setFont(new java.awt.Font("Liberation Serif", 1, 48)); // NOI18N
        lblRating1.setForeground(new java.awt.Color(102, 102, 255));
        lblRating1.setText("RECOMENEM");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAfegirResenya, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarUsuari1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRating1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                            .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(423, 423, 423))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addComponent(imgLogo)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgLogo)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(txtNom)
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRating1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAfegirResenya, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarUsuari1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        frmLog log = new frmLog();
        log.setVisible(true);
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnControlUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlUsuariActionPerformed
        // TODO add your handling code here:
        frmControlUsuaris fUsuaris = new frmControlUsuaris();
        fUsuaris.setVisible(true);
    }//GEN-LAST:event_btnControlUsuariActionPerformed

    private void btnDiccionariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiccionariActionPerformed
        // TODO add your handling code here:
        frmDiccionari diccionari = new frmDiccionari();
        diccionari.setVisible(true);
    }//GEN-LAST:event_btnDiccionariActionPerformed

    private void btnControlResenyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlResenyesActionPerformed
        // TODO add your handling code here:
        frmLlistaResenyes resenyes = new frmLlistaResenyes();
        resenyes.setVisible(true);
    }//GEN-LAST:event_btnControlResenyesActionPerformed

    private void btnControlContingutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlContingutActionPerformed
        // TODO add your handling code here:
        frmContingutPagina fContingut = new frmContingutPagina();
        fContingut.setVisible(true);

    }//GEN-LAST:event_btnControlContingutActionPerformed

    private void btnModificarUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuariActionPerformed
        frmHigherLower fhigherLower = new frmHigherLower();
        fhigherLower.setVisible(true);
    }//GEN-LAST:event_btnModificarUsuariActionPerformed

    private void btnAfegirResenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirResenyaActionPerformed
        frmMainClient fMain = new frmMainClient();
        fMain.setVisible(true);
    }//GEN-LAST:event_btnAfegirResenyaActionPerformed

    private void btnModificarUsuari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuari1ActionPerformed
        frmEdicioUsuari fEdicioUsuari = new frmEdicioUsuari();
        fEdicioUsuari.setVisible(true);
    }//GEN-LAST:event_btnModificarUsuari1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        for (Window w : Window.getWindows()) {
            w.dispose();
        }
        frmLogin flogin = new frmLogin();
        flogin.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPanelControl().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirResenya;
    private javax.swing.JButton btnControlContingut;
    private javax.swing.JButton btnControlResenyes;
    private javax.swing.JButton btnControlUsuari;
    private javax.swing.JButton btnDiccionari;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModificarUsuari;
    private javax.swing.JButton btnModificarUsuari1;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblRating1;
    private javax.swing.JPanel panAdmin;
    private javax.swing.JLabel txtImage;
    private javax.swing.JLabel txtNom;
    private javax.swing.JLabel txtNota;
    // End of variables declaration//GEN-END:variables
}
